
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''


# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# カーソル位置のコンテキストのftを判定するライブラリ
[[plugins]]  
repo = 'Shougo/context_filetype.vim'

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'



 

[[plugins]]
repo = 'Shougo/neocomplete.vim'


[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/syntastic'


[[plugins]]
repo = 'szw/vim-tags'
