[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
  " select area and put enter then type characters
  vmap <Enter> <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " startup NerdTree after vim enter
  " autocmd VimEnter * execute 'NERDTree'

  " open or close NerdTree with Ctrl+e
  " map <C-e> :NERDTreeToggle<CR>

  " show hidden file
  let NERDTreeShowHidden = 1

  " set window width size
  let g:NERDTreeWinSize=20

  " キーマップの設定
  nnoremap s <Nop>
  nnoremap sj <C-w>j
  nnoremap sk <C-w>k
  nnoremap sl <C-w>l
  nnoremap sh <C-w>h
  nnoremap sJ <C-w>J
  nnoremap sK <C-w>K
  nnoremap sL <C-w>L
  nnoremap sH <C-w>H
  nnoremap sn gt
  nnoremap sp gT
  nnoremap sr <C-w>r
  nnoremap s= <C-w>=
  nnoremap sw <C-w>w
  nnoremap so <C-w>_<C-w>|
  nnoremap sO <C-w>=
  nnoremap sN :<C-u>bn<CR>
  nnoremap sP :<C-u>bp<CR>
  nnoremap st :<C-u>tabnew<CR>
  nnoremap sT :<C-u>Unite tab<CR>
  nnoremap ss :<C-u>sp<CR>
  nnoremap sv :<C-u>vs<CR>
  nnoremap sq :<C-u>q<CR>
  nnoremap sQ :<C-u>bd<CR>
  nnoremap sb :<C-u>Unite buffer_tab -buffer-name=file<CR>
  nnoremap sB :<C-u>Unite buffer -buffer-name=file<CR>

  call submode#enter_with('bufmove', 'n', '', 's>', '<C-w>>')
  call submode#enter_with('bufmove', 'n', '', 's<', '<C-w><')
  call submode#enter_with('bufmove', 'n', '', 's+', '<C-w>+')
  call submode#enter_with('bufmove', 'n', '', 's-', '<C-w>-')
  call submode#map('bufmove', 'n', '', '>', '<C-w>>')
  call submode#map('bufmove', 'n', '', '<', '<C-w><')
  call submode#map('bufmove', 'n', '', '+', '<C-w>+')
  call submode#map('bufmove', 'n', '', '-', '<C-w>-')

" when open nerdtree, the cursor is on the file
function s:MoveToFileAtStart()
  call feedkeys("\<Space>")
  call feedkeys("\s")
  call feedkeys("\l")
endfunction

autocmd VimEnter *  NERDTree | call s:MoveToFileAtStart() 
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
   " トグル設定
   map <C-e> <plug>NERDTreeTabsToggle<CR>
   " 起動時有効
   let g:nerdtree_tabs_open_on_console_startup=1
   " 起動時にファイルにカーソルを合わせる
   function! s:MoveCursorAtStart()
       call feedkeys("\<C-l>")
   endfunction
   autocmd VimEnter * NERDTree | call s:MoveCursorAtStart()
'''
depends = ['nerdtree']

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  " Smarter tab line turn on
  let g:airline#extensions#tabline#enabled = 1
  " use powerline font
  let g:airline_powerline_fonts = 1
  " （タブが一個の場合）バッファのリストをタブラインに表示する機能をオフ
  let g:airline#extensions#tabline#show_buffers = 0
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  " indent line type |
  set list lcs=tab:\|\
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  " show hidden file
  let g:ctrlp_show_hidden = 1
'''

 [[plugins]]
 repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
  let g:deoplete#ignore_sources.php = ['omni']

  " disable the tern preview window
  set completeopt-=preview
'''

 [[plugins]]
 repo = 'tyrannicaltoucan/vim-deep-space'
 hook_add = '''
   set background=dark
   set termguicolors
   colorscheme deep-space
 '''

 [[plugins]]
 repo = 'miyakogi/seiya.vim'
 hook_add = '''
   " Default value: ['ctermbg']
   let g:seiya_target_groups = has('nvim') ? ['guibg'] : ['ctermbg']
 '''

# [[plugins]]
# repo = 'kristijanhusak/vim-hybrid-material'
# hook_add = '''
#  let g:enable_bold_font = 1
#  let g:enable_italic_font = 1
#  set background=dark
#  colorscheme hybrid_material
# '''

