# 補完
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['js']
depends = ['deoplete.nvim']

[[plugins]] #js syntax
repo = 'othree/yajs.vim'
on_ft = ['js']

[[plugins]] #js fommater
repo = 'prettier/vim-prettier'
on_ft = ['js']
hook_add = '''
  let g:prettier#quickfix_enabled = 0
  let g:prettier#autoformat = 0
  autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.scss,*.json,*.graphql,*.vue Prettier
'''
