#------------------------------------
# for php
#------------------------------------
 [[plugins]] #debugger interface with xdebug
 repo = 'joonty/vdebug'
 on_ft = ['php']

 
 [[plugins]] #blade syntax
 repo = 'jwalton512/vim-blade'
 on_ft = ['php', 'blade']
 
 [[plugins]] #php formatter
 repo = 'beanworks/vim-phpfmt'
 on_ft = ['php']
 hook_add = '''
     let g:phpfmt_standard = 'PSR2'
     let g:phpfmt_autosave = 1
 '''
 [[plugins]] #php completion
 repo = 'lvht/phpcd.vim'
 on_ft = ['php']
#------------------------------------
